package TackleIt.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ProblemOfComparableMagnitude_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Tackle_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new TackleIt_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new TacklePass_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Trouble_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new TroubleAndTackles_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9fba857L), MetaIdFactory.conceptId(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f93f01L), MetaIdFactory.conceptId(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f91ee9L), MetaIdFactory.conceptId(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341fa01a5acL), MetaIdFactory.conceptId(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f93f00L), MetaIdFactory.conceptId(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f91eeaL)).seal();
}
