package TackleIt.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptProblemOfComparableMagnitude = createDescriptorForProblemOfComparableMagnitude();
  /*package*/ final ConceptDescriptor myConceptTackle = createDescriptorForTackle();
  /*package*/ final ConceptDescriptor myConceptTackleIt = createDescriptorForTackleIt();
  /*package*/ final ConceptDescriptor myConceptTacklePass = createDescriptorForTacklePass();
  /*package*/ final ConceptDescriptor myConceptTrouble = createDescriptorForTrouble();
  /*package*/ final ConceptDescriptor myConceptTroubleAndTackles = createDescriptorForTroubleAndTackles();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptProblemOfComparableMagnitude, myConceptTackle, myConceptTackleIt, myConceptTacklePass, myConceptTrouble, myConceptTroubleAndTackles);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ProblemOfComparableMagnitude:
        return myConceptProblemOfComparableMagnitude;
      case LanguageConceptSwitch.Tackle:
        return myConceptTackle;
      case LanguageConceptSwitch.TackleIt:
        return myConceptTackleIt;
      case LanguageConceptSwitch.TacklePass:
        return myConceptTacklePass;
      case LanguageConceptSwitch.Trouble:
        return myConceptTrouble;
      case LanguageConceptSwitch.TroubleAndTackles:
        return myConceptTroubleAndTackles;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForProblemOfComparableMagnitude() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TackleIt", "ProblemOfComparableMagnitude", 0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9fba857L);
    b.class_(false, false, false);
    b.origin("r:c3b08c25-3a65-47dd-9386-4d105e05313b(TackleIt.structure)/6586166193210239063");
    b.version(2);
    b.property("description", 0x5b66c341f9fba858L).type(PrimitiveTypeId.STRING).origin("6586166193210239064").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTackle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TackleIt", "Tackle", 0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f93f01L);
    b.class_(false, false, false);
    b.origin("r:c3b08c25-3a65-47dd-9386-4d105e05313b(TackleIt.structure)/6586166193210081025");
    b.version(2);
    b.property("description", 0x5b66c341f9f93f02L).type(PrimitiveTypeId.STRING).origin("6586166193210081026").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTackleIt() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TackleIt", "TackleIt", 0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f91ee9L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c3b08c25-3a65-47dd-9386-4d105e05313b(TackleIt.structure)/6586166193210072809");
    b.version(2);
    b.property("showTackles", 0x5b66c341f9fc7ee6L).type(PrimitiveTypeId.BOOLEAN).origin("6586166193210293990").done();
    b.property("showProblemsOfComparableMagnitude", 0x5b66c341f9fc7ee8L).type(PrimitiveTypeId.BOOLEAN).origin("6586166193210293992").done();
    b.aggregate("troubleAndTackles", 0x5b66c341f9f91eebL).target(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f91eeaL).optional(true).ordered(true).multiple(true).origin("6586166193210072811").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTacklePass() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TackleIt", "TacklePass", 0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341fa01a5acL);
    b.class_(false, false, false);
    b.origin("r:c3b08c25-3a65-47dd-9386-4d105e05313b(TackleIt.structure)/6586166193210631596");
    b.version(2);
    b.aggregate("passOne", 0x5b66c341fa01a5adL).target(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f93f01L).optional(true).ordered(true).multiple(true).origin("6586166193210631597").done();
    b.aggregate("passTwo", 0x5b66c341fa01a5afL).target(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f93f01L).optional(true).ordered(true).multiple(true).origin("6586166193210631599").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTrouble() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TackleIt", "Trouble", 0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f93f00L);
    b.class_(false, false, false);
    b.origin("r:c3b08c25-3a65-47dd-9386-4d105e05313b(TackleIt.structure)/6586166193210081024");
    b.version(2);
    b.property("description", 0x5b66c341f9f93f08L).type(PrimitiveTypeId.STRING).origin("6586166193210081032").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTroubleAndTackles() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("TackleIt", "TroubleAndTackles", 0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f91eeaL);
    b.class_(false, false, false);
    b.origin("r:c3b08c25-3a65-47dd-9386-4d105e05313b(TackleIt.structure)/6586166193210072810");
    b.version(2);
    b.aggregate("trouble", 0x5b66c341f9f95c76L).target(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f93f00L).optional(false).ordered(true).multiple(false).origin("6586166193210088566").done();
    b.aggregate("passOneTackles", 0x5b66c341f9f979fdL).target(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f93f01L).optional(true).ordered(true).multiple(true).origin("6586166193210096125").done();
    b.aggregate("passTwoTackles", 0x5b66c341fa007cbdL).target(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9f93f01L).optional(true).ordered(true).multiple(true).origin("6586166193210555581").done();
    b.aggregate("problemsOfComparableMagnitude", 0x5b66c341f9fba85aL).target(0x38ae19b1540f43ecL, 0x83787a6f9a38ea5eL, 0x5b66c341f9fba857L).optional(true).ordered(true).multiple(true).origin("6586166193210239066").done();
    return b.create();
  }
}
